name: afkTimeskip
version: '1.0-SNAPSHOT'
main: org.possess.afktimeskip.AfkTimeskip
api-version: '1.21'

commands:
  afk:
    description: Toggle AFK status
    usage: /<command>
  afkreload:
    description: Reload the plugin configuration
    usage: /<command>
    permission: afktimeskip.reload

permissions:
  afktimeskip.reload:
    description: Allows reloading the plugin configuration
    default: op